### ISSUE TITLE
GUI not starting on macOS Mojave

### ISSUE THREAD

**Issue by goldingn** [remi-daigle/MarxanConnect#62]
The Marxan Connect GUI appears to install fine, but doesn't open for me. I'm on macOS Mojave (10.14.3)

I followed the instructions [here](http://marxanconnect.ca/#macos_(yosemite_10105)) to install version 0.1.2. The installation proceeded exactly as described, including control-clicking to open and authorise the app. The app is now installed and has a security exception allowing it to be opened, however the app just doesn't start. There are no error messages or other notifications, nor does any new process appear to start in the background. I've waited up to 15 minutes, but still nothing happening.

Sorry there's no more information I can think of to help debug this, let me know if there's any information you can think of. I'd rather not have to try installing from source, but can give that a go if there's no other way.

P.S. I'm AE for the manuscript at MEE, and need to try out the software and tutorial before I can make a decision.

**Comment by goldingn** [comment]
**correction**: I do see this rather uninformative notification when I try to open the app from Spotlight
![Screen Shot 2019-03-11 at 3 17 14 pm](https://user-images.githubusercontent.com/4450731/54100104-df6ae180-4410-11e9-88c4-4d6f4fbda6e6.png)

**Comment by remi-daigle** [comment]
So sorry @goldingn! I hadn't seen this until now! I weirdly never received a notification about this issue!

This is very disheartening! We've tested the app on a collection of virtual machines and also a few actual Mac's that the author team had access to and no one has had any problems. I just double checked and it works on 10.14 (but I don't have access to 10.14.3). I'm not sure I will have access to 10.14.3, but I will update one of my virtual machines to 10.14.4 and report back!

**Comment by remi-daigle** [comment]
Update: It works fine on 10.14.4 which suggests it's not a general Mac version issue. Just to be sure I going to created a brand new VM with no ties to Marxan Connect (i.e. no python 3.x installations, no Marxan Connect previous installs, etc) and it still worked perfectly fine.

I suspect there is something 'unique' about your machine that's not allowing it to work, I really don't know what the issue could be without more info. A couple things I can think of that we can try:

- do you have access to other machines? If so, can you try installing elsewhere?
- on your machine, can you open a terminal and try opening the app from there. That might give me more information about the problem.

```
open /Applications/MarxanConnectGUI.app
```

**Comment by remi-daigle** [comment]
Yet another update:

It does seem like 'something' related to python packages is not properly bundled. It does not work on a brand new VM and the error (or lack thereof is the same as you found). This is now a matter of finding the offending python package. One of the culprits is in here:
`conda create --name marcon wxpython matplotlib geopandas descartes shapely pandas numpy basemap basemap-data-hires
`

**Comment by goldingn** [comment]
No worries, I've missed issues on my repos for years at a time before :)

It has happened for me when I've not been watching my own repo. If that's the issue for you, you can click this button in the top right:
![Screen Shot 2019-03-29 at 9 35 49 am](https://user-images.githubusercontent.com/4450731/55197257-1fe69f80-5206-11e9-8b51-1a30280ce59d.png)


Glad you've managed to replicate it some what! Let me know when there's something I can do to help.

**Comment by remi-daigle** [comment]
I definitely was watching the repo, and I got notified when you replied, but strangely nothing from the original issue... bizarre!

I've got the bug narrowed down to a single file `epsg` that gets installed when you install anaconda and `conda create --name marcon proj4`. Currently having trouble doing something about it! Something seems hard coded to be looking for that file in `Anaconda3\envs\marcon\share\proj\epsg`.

**Comment by remi-daigle** [comment]
I believe v0.1.3 fixes this issue, can you confirm?

**Comment by goldingn** [comment]
Sorry for leaving this for so long. Yes, it works! Closing now

**Comment by goldingn** [comment]
Unfortunately I'm having this same issue with the latest release: 0.1.5. I tried twice following the instructions exactly. Installation of 0.1.4 worked fine.

**Comment by remi-daigle** [comment]
Well I am very surprised again! 

The changes between 0.1.4 and 0.1.5 were quite minor and I didn't think anything would break! I'm currently working on 0.1.6 and it will have some fairly major changes, both behind the scenes (replacing the soon to be deprecated `Basemap` with the newer `cartopy`) and part of the GUI (editing and releasing the post-hoc tab #71 ). 

All of this will come with extensive testing, but my testing machine is currently in the shop. Stay tuned, hopefully this is easy to resolve!

**Comment by goldingn** [comment]
Thanks for looking into it. I know how hard it is to resolve intermittent and system-specific bugs like this!

**Comment by ptg732** [comment]
I Remi
It seems the problem is back with the version 0.1.6 under MacOS 14.2.1 (Sonoma). Attached you can find the error report if you are still active with Marxan Connect

[Error report.txt](https://github.com/remi-daigle/MarxanConnect/files/13917343/Error.report.txt)
