### ISSUE TITLE
Generate New Input File from Template

### ISSUE THREAD

**Issue by JamieLeighSmyth** [remi-daigle/MarxanConnect#63]
#### Description
When attempting to  generate a new input file from template in the Run Marxan Tab, it does not allow you to create a new file when you click browse to set the file path. You must choose an already existing file and overwrite an old input file to generate a new one. 

#### Screenshots
![image](https://user-images.githubusercontent.com/49280776/55568348-e9ad9200-56d5-11e9-9a7d-892fe7dc1fe7.png)

#### Files
Input.dat files 

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks
Include specific tasks in the order they need to be done in.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Remember to use helpful labels (e.g. bug, wishlist, etc).

**Comment by remi-daigle** [comment]
Thanks for pointing this out @JamieLeighSmyth !

It'll now be fixed in the next release.
