### ISSUE TITLE
Links do not open in Getting Started

### ISSUE THREAD

**Issue by goldingn** [remi-daigle/MarxanConnect#64]
The Getting Started window that opened up when I first opened the app (v1.1.3, on macOS 10.14.4) has two links 'Tutorial' and 'Glossary'. These fail to open, with the following error:
![Screen Shot 2019-05-10 at 3 29 34 pm](https://user-images.githubusercontent.com/4450731/57504742-f9ee0800-7338-11e9-9ac1-99c3d542671d.png)

Not sure if it's the backslash or the relative path that's causing this.

**Comment by remi-daigle** [comment]
Very strange! This works perfectly on windows. Seems to be a relative path issue specific to the `HyperlinkCtrl` function and I honestly don't know how to solve it. I do know that I have functions that I can pipe into a button that work on windows and mac, so I'm just going to give up on hyperlinks and replace them with buttons.

**Comment by remi-daigle** [comment]
In the next release, there will be buttons instead of hyperlinks. it now works for windows and mac. Thanks for spotting this one!
