### ISSUE TITLE
README links 404

### ISSUE THREAD

**Issue by trashbirdecology** [remi-daigle/MarxanConnect#84]
Multiple links in readme are 404. E.g., "Tutorial" <https://github.com/remi-daigle/MarxanConnect/blob/master/tutorial.html>

**Comment by remi-daigle** [comment]
You're 100% right!

I generate the readme from the same file as the main page of the main [website](https://marxanconnect.ca). For now, try out those links on the website. I'll try fixing those readme links soon!

Are you just accessing the readme via github?

**Comment by trashbirdecology** [comment]
yes

**Comment by remi-daigle** [comment]
Should be good now?
